# Setup and configuring aicoe-ci with configuration file `.aicoe-ci.yaml`
# Example `.aicoe-ci.yaml` with a full list of config options is available here: https://github.com/AICoE/aicoe-ci/blob/master/docs/.aicoe-ci.yaml
---
check:
  - thoth-build
build:
  build-stratergy: Source
  base-image: "quay.io/thoth-station/s2i-minimal-py38-notebook:v0.4.0"
  registry: quay.io
  registry-org: thoth-station
  registry-project: s2i-ray-ml-notebook
  registry-secret: thoth-station-thoth-pusher-secret
